_BASE_: [
  './_base_/models/mask_rcnn_r50_fpn.yml',
  './_base_/optimizers/rcnn_1x.yml',
  './_base_/datasets/coco_debug.yml',
  './_base_/readers/mask_fpn_reader_debug.yml',
  './_base_/runtime_debug.yml',
]
