architecture: FCOS
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
weights: output/fcos_r50_fpn_1x/model_final
load_static_weights: True

# Model Achitecture
FCOS:
  # model feat info flow
  backbone: ResNet
  neck: FPN
  fcos_head: FCOSHead
  # post process
  bbox_post_process: BBoxPostProcess

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: affine_channel
  norm_decay: 0.
  freeze_at: 0
  return_idx: [1,2,3]
  num_stages: 3

FPN:
  # index 0 stands for res2
  in_channels: [256, 512, 1024, 2048]
  out_channel: 256
  min_level: 1
  max_level: 5
  spatial_scale: [0.125, 0.0625, 0.03125]
  has_extra_convs: true
  use_c5: false

# Anchor:
#   anchor_generator:
#     name: AnchorGeneratorRPN
#     aspect_ratios: [0.5, 1.0, 2.0]
#     anchor_start_size: 32
#     stride: [4., 4.]
#   anchor_target_generator:
#     name: AnchorTargetGeneratorRPN
#     batch_size_per_im: 256
#     fg_fraction: 0.5
#     negative_overlap: 0.3
#     positive_overlap: 0.7
#     straddle_thresh: 0.0

# RPNHead:
#   rpn_feat:
#     name: RPNFeat
#     feat_in: 256
#     feat_out: 256
#   anchor_per_position: 3
#   rpn_channel: 256

FCOSHead:
  fcos_feat:
    name: FCOSFeat
    feat_in: 256
    feat_out: 256 
    num_convs: 4
    norm_type: "gn" #
  num_classes: 80
  fpn_stride: [8, 16, 32, 64, 128]
  prior_prob: 0.01
  fcos_loss: FCOSLoss
  norm_reg_targets: True
  centerness_on_reg: True
  use_dcn_in_tower: False

# RetinaHead:
#   num_convs_per_octave: 4
#   num_chan: 256
#   max_level: 7
#   min_level: 3
#   prior_prob: 0.01
#   base_scale: 4
#   num_scales_per_octave: 3
#   anchor_generator:
#     aspect_ratios: [1.0, 2.0, 0.5]
#     variance: [1.0, 1.0, 1.0, 1.0]
#   target_assign:
#     positive_overlap: 0.5
#     negative_overlap: 0.4
#   gamma: 2.0
#   alpha: 0.25
#   sigma: 3.0151134457776365
#   output_decoder:
#     score_thresh: 0.05
#     nms_thresh: 0.5
#     pre_nms_top_n: 1000
#     detections_per_im: 100
#     nms_eta: 1.0

FCOSLoss:
  loss_alpha: 0.25
  loss_gamma: 2.0
  iou_loss_type: "giou"
  reg_weights: 1.0

BBoxPostProcess:
  decode:
    name: FCOSBox #
    num_classes: 80
    batch_size: 1
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.025
    nms_threshold: 0.6
    background_label: -1 #
