worker_num: 2
TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'fcos_target'] #
  sample_transforms:
  - DecodeImage: {to_rgb: true}
  - RandomFlipImage: {prob: 0.5}
  - NormalizeImage: {is_channel_first: false, is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - ResizeImage: {target_size: 800, max_size: 1333, interp: 1, use_cv2: true}
  - Permute: {to_bgr: false, channel_first: true}
  batch_transforms:
  - PadBatch: {pad_to_stride: 128, use_padded_im_info: false, pad_gt: true}
  - Gt2FCOSTarget: {object_sizes_boundary: [64, 128, 256, 512], center_sampling_radius: 1.5, downsample_ratios: [8, 16, 32, 64, 128], norm_reg_targets: True}
  batch_size: 1
  shuffle: true # drop_last: true # maskrcnn
  use_process: false # oldfcos +


EvalReader:
  inputs_def:
    fields: ['image', 'im_shape', 'scale_factor', 'im_id'] # ['image', 'im_id', 'im_shape', 'im_info'] # oldfcos
  sample_transforms:
  - DecodeOp: {to_rgb: true} # oldfcos +, with_mixup: false # fcos +
  - NormalizeImageOp: {is_channel_first: false, is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - ResizeOp: {interp: 1, target_size: [800, 1333]} # interp: 1, use_cv2: true # oldfcos
  - PermuteOp: {channel_first: true, to_bgr: false} # oldfcos +
  batch_transforms:
  - PadBatchOp: {pad_to_stride: 128, use_padded_im_info: true} # pad_to_stride: 32, pad_gt: false # maskrcnn
  batch_size: 1
  shuffle: false
  worker_num: 1 # oldfcos +
  use_process: false # oldfcos +

TestReader:
  inputs_def:
    fields: ['image', 'im_shape', 'scale_factor', 'im_id']
  sample_transforms:
  - DecodeOp: {to_rgb: true}
  - NormalizeImageOp: {is_channel_first: false, is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - ResizeOp: {interp: 1, target_size: [800, 1333], interp: 1, use_cv2: true} # oldfcos
  - PermuteOp: {channel_first: true, to_bgr: false}
  batch_transforms:
  - PadBatchOp: {pad_to_stride: 128, use_padded_im_info: true}
  batch_size: 1
  shuffle: false
